services:

  postgres:
    image: postgres:16
    container_name: bolao_postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data_1:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: bolao_api
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      NODE_ENV: development
volumes:
  postgres_data_1: