CREATE TABLE users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar NOT NULL,
  email varchar UNIQUE NOT NULL,
  senha_hash varchar NOT NULL,
  pontuacao_total integer DEFAULT 0,
  role varchar DEFAULT 'USER',
  created_at timestamp DEFAULT (now())
);

CREATE TABLE times (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar NOT NULL,
  sigla varchar(3) UNIQUE NOT NULL,
  escudo_url varchar
);

CREATE TABLE boloes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar NOT NULL,
  criador_id integer NOT NULL REFERENCES users(id),
  created_at timestamp DEFAULT (now())
);

CREATE TABLE jogos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  time_a_id integer NOT NULL REFERENCES times(id),
  time_b_id integer NOT NULL REFERENCES times(id),
  data_jogo timestamp NOT NULL,
  gol_a_real integer,
  gol_b_real integer,
  status varchar DEFAULT 'AGENDADO'
);

CREATE TABLE bolao_jogos (
  bolao_id integer NOT NULL REFERENCES boloes(id) ON DELETE CASCADE,
  jogo_id integer NOT NULL REFERENCES jogos(id) ON DELETE CASCADE,
  PRIMARY KEY (bolao_id, jogo_id)
);

CREATE TABLE participantes_bolao (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bolao_id integer NOT NULL REFERENCES boloes(id) ON DELETE CASCADE,
  user_id integer REFERENCES users(id),
  nome_avulso varchar,
  pontuacao_no_bolao integer DEFAULT 0,
  data_entrada timestamp DEFAULT (now())
);

CREATE TABLE palpites (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bolao_id integer NOT NULL REFERENCES boloes(id) ON DELETE CASCADE,
  participante_id integer NOT NULL REFERENCES participantes_bolao(id) ON DELETE CASCADE,
  jogo_id integer NOT NULL REFERENCES jogos(id),
  gol_a_palpite integer NOT NULL,
  gol_b_palpite integer NOT NULL,
  pontos_ganhos integer DEFAULT 0,
  data_palpite timestamp DEFAULT (now())
);

-- Índices
-- Garante apenas 1 palpite por participante por jogo
CREATE UNIQUE INDEX idx_palpite_unico ON palpites (participante_id, jogo_id);

-- Comentários
COMMENT ON COLUMN users.pontuacao_total IS 'Soma de todos os pontos ganhos';
COMMENT ON COLUMN times.escudo_url IS 'Link para o logo do time';
COMMENT ON COLUMN jogos.gol_a_real IS 'NULL enquanto o jogo não acontecer';
COMMENT ON COLUMN jogos.gol_b_real IS 'NULL enquanto o jogo não acontecer';
COMMENT ON COLUMN jogos.status IS 'AGENDADO, EM_ANDAMENTO, FINALIZADO';
COMMENT ON COLUMN palpites.pontos_ganhos IS 'Calculado após o fim do jogo';
COMMENT ON COLUMN participantes_bolao.pontuacao_no_bolao IS 'Pontos específicos deste bolão';
COMMENT ON COLUMN participantes_bolao.nome_avulso IS 'Preenchido apenas se user_id for NULL';

-- Constraints
ALTER TABLE palpites 
ADD CONSTRAINT check_gol_a_palpite_negativo CHECK (gol_a_palpite >= 0),
ADD CONSTRAINT check_gol_b_palpite_negativo CHECK (gol_b_palpite >= 0);

ALTER TABLE jogos
ADD CONSTRAINT check_gol_a_real_negativo CHECK (gol_a_real >= 0),
ADD CONSTRAINT check_gol_b_real_negativo CHECK (gol_b_real >= 0);