CREATE TABLE users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar NOT NULL,
  email varchar UNIQUE NOT NULL,
  senha_hash varchar NOT NULL,
  pontuacao_total integer DEFAULT 0,
  created_at timestamp DEFAULT (now())
);

CREATE TABLE times (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar NOT NULL,
  sigla varchar(3) UNIQUE NOT NULL,
  escudo_url varchar
);

CREATE TABLE boloes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar NOT NULL,
  criador_id integer NOT NULL,
  created_at timestamp DEFAULT (now())
);

CREATE TABLE jogos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  time_a_id integer NOT NULL,
  time_b_id integer NOT NULL,
  data_jogo timestamp NOT NULL,
  gol_a_real integer,
  gol_b_real integer,
  status varchar DEFAULT 'AGENDADO'
);

CREATE TABLE palpites (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bolao_id integer NOT NULL,
  user_id integer NOT NULL,
  jogo_id integer NOT NULL,
  gol_a_palpite integer NOT NULL,
  gol_b_palpite integer NOT NULL,
  pontos_ganhos integer DEFAULT 0,
  data_palpite timestamp DEFAULT (now())
);

CREATE TABLE participantes_bolao (
  bolao_id integer NOT NULL,
  user_id integer NOT NULL,
  pontuacao_no_bolao integer DEFAULT 0,
  data_entrada timestamp DEFAULT (now()),
  PRIMARY KEY (bolao_id, user_id)
);

CREATE TABLE bolao_jogos (
  bolao_id integer NOT NULL REFERENCES boloes(id) ON DELETE CASCADE,
  jogo_id integer NOT NULL REFERENCES jogos(id) ON DELETE CASCADE,
  PRIMARY KEY (bolao_id, jogo_id)
);

CREATE UNIQUE INDEX ON palpites (bolao_id, user_id, jogo_id);

COMMENT ON COLUMN users.pontuacao_total IS 'Soma de todos os pontos ganhos';

COMMENT ON COLUMN times.escudo_url IS 'Link para o logo do time';

COMMENT ON COLUMN jogos.gol_a_real IS 'NULL enquanto o jogo não acontecer';

COMMENT ON COLUMN jogos.gol_b_real IS 'NULL enquanto o jogo não acontecer';

COMMENT ON COLUMN jogos.status IS 'AGENDADO, EM_ANDAMENTO, FINALIZADO';

COMMENT ON COLUMN palpites.pontos_ganhos IS 'Calculado após o fim do jogo';

COMMENT ON COLUMN participantes_bolao.pontuacao_no_bolao IS 'Pontos específicos deste bolão';

ALTER TABLE boloes ADD FOREIGN KEY (criador_id) REFERENCES users (id);

ALTER TABLE jogos ADD FOREIGN KEY (time_a_id) REFERENCES times (id);

ALTER TABLE jogos ADD FOREIGN KEY (time_b_id) REFERENCES times (id);

ALTER TABLE palpites ADD FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE palpites ADD FOREIGN KEY (jogo_id) REFERENCES jogos (id);

ALTER TABLE participantes_bolao ADD FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE participantes_bolao ADD FOREIGN KEY (bolao_id) REFERENCES boloes (id);

ALTER TABLE palpites ADD FOREIGN KEY (bolao_id) REFERENCES boloes (id);

ALTER TABLE users ADD COLUMN role varchar DEFAULT 'USER';


ALTER TABLE palpites 
ADD CONSTRAINT check_gol_a_negativo CHECK (gol_a_palpite >= 0),
ADD CONSTRAINT check_gol_b_negativo CHECK (gol_b_palpite >= 0);

ALTER TABLE jogos
ADD CONSTRAINT check_gol_a_negativo CHECK (gol_a_real >= 0),
ADD CONSTRAINT check_gol_b_negativo CHECK (gol_b_real >= 0);